
language: java

jdk:
- oraclejdk8
- oraclejdk9
- openjdk8

matrix:
  allow_failures:
  - jdk: oraclejdk9
  
install:
 - apt-get install nmap
 - add-apt-repository ppa:cpick/hub
 - apt-get install hub
